/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package melilliselect;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author arsam
 */
public class Dashboard extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */
    JPanel dashboard ;
    public Dashboard() {
    
        initComponents();
//        setVisible(true);
        add(new TopNav(), BorderLayout.PAGE_START);
        dashboard = new FileExplorer();
        add(dashboard,BorderLayout.CENTER);
    
    }
    public void dashboardChange(JPanel jPanel){
        remove(dashboard);
        removeNotify();
        
        dashboard = jPanel;
        add(jPanel,BorderLayout.CENTER);
        addNotify();
        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(242, 241, 240));
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
