/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package melilliselect;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Insets;
import java.text.MessageFormat;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.border.Border;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import melilliselect.Models.FileManager;
import melilliselect.Models.LeftOnlyBorder;

/**
 *
 * @author arsam
 */
public class SideNav extends javax.swing.JPanel {

    /**
     * Creates new form SIdeNav
     */
    private String Selected = "1";
    private final String sText = "Scelte: {0}/120";
    private final String dText = "Dettagli: {0}";

    public String getSelected() {
        return Selected;

    }

    public void setSelected(String Selected) {
        this.Selected = Selected;
    }

    public SideNav() {
        updateSeleted();
        updateCount();
    }

    public void updateSeleted() {
        initComponents();
        Border b1 = new LeftOnlyBorder(5, StaticData.fgPinkColor);
        if (Selected == "1") {
            jButton1.setForeground(StaticData.fgPinkColor);
            jPanel4.setBorder(b1);
            jButton1.setIcon(new ImageIcon(getClass().getResource("/melilliselect/resources/seletecdImage.png"))); // NOI18N
        } else if (Selected == "2") {
            jButton2.setForeground(StaticData.fgPinkColor);
            jPanel5.setBorder(b1);
            jButton2.setIcon(new ImageIcon(getClass().getResource("/melilliselect/resources/pinkHeart.png"))); // NOI18N
        } else if (Selected == "3") {
            jButton3.setForeground(StaticData.fgPinkColor);
            jPanel6.setBorder(b1);
            jButton3.setIcon(new ImageIcon(getClass().getResource("/melilliselect/resources/pinkClock.png"))); // NOI18N
        } else if (Selected == "4") {
            jButton4.setForeground(StaticData.fgPinkColor);
            jPanel7.setBorder(b1);
            jButton4.setIcon(new ImageIcon(getClass().getResource("/melilliselect/resources/pinkSend.png"))); // NOI18N
        } else if (Selected == "5") {
            jButton5.setForeground(StaticData.fgPinkColor);
            jPanel9.setBorder(b1);
            jButton5.setIcon(new ImageIcon(getClass().getResource("/melilliselect/resources/settingsPink.png"))); // NOI18N
        }
    }

    public void updateCount() {
        jLabel3.setText(MessageFormat.format(sText, FileManager.totalLiked));
        jLabel4.setText(MessageFormat.format(dText, FileManager.totalDiamond));
    }

    public void updateLikeCount(boolean liked) {
        if (liked) {
            FileManager.totalLiked++;
        } else {
            FileManager.totalLiked--;
        }
        updateCount();
    }

    public void updateDiamondCount(boolean liked) {
        if (liked) {
            FileManager.totalDiamond++;
        } else {
            FileManager.totalDiamond--;
        }
        updateCount();
    }

    @Override
    public void repaint() {
        removeAll();
        updateSeleted();
        updateCount();
        super.repaint(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody

    }

    
    public void updateDashboardForce(String num, JPanel jp) {
        MainMenu.dashboard.dashboardChange(jp);
        this.Selected = num;
        repaint();
    }
    
    public void updateDashboard(String num, JPanel jp) {
        if(StaticData.fileManager.getSettingsModel()!=null){
        MainMenu.dashboard.dashboardChange(jp);
        this.Selected = num;
        repaint();
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(27, 41, 63));
        setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(StaticData.blueBackground);

        jLabel5.setBackground(StaticData.blueBackground);
        jLabel5.setFont(StaticData.font12);
        jLabel5.setForeground(new java.awt.Color(56, 83, 124));
        jLabel5.setText("Version 1.0");
        jLabel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(22, 22, 22))
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(StaticData.blueBackground);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melilliselect/resources/Logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18))
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(StaticData.blueBackground);

        jPanel4.setBackground(StaticData.blueBackground);

        jButton1.setBackground(StaticData.blueBackground);
        jButton1.setFont(StaticData.font13);
        jButton1.setForeground(StaticData.textWhiteColor);
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melilliselect/resources/ImageIcon.png"))); // NOI18N
        jButton1.setText("Foto");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        jButton1.setFocusPainted(false);
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setIconTextGap(16);
        jButton1.setMargin(new java.awt.Insets(2, -500, 2, 14));
        jButton1.setOpaque(true);
        jButton1.setPreferredSize(new java.awt.Dimension(55, 25));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel5.setBackground(StaticData.blueBackground);

        jButton2.setBackground(StaticData.blueBackground);
        jButton2.setFont(StaticData.font13);
        jButton2.setForeground(StaticData.textWhiteColor);
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melilliselect/resources/heartSide.png"))); // NOI18N
        jButton2.setText("Selezione");
        jButton2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        jButton2.setFocusPainted(false);
        jButton2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton2.setIconTextGap(16);
        jButton2.setMargin(new java.awt.Insets(2, -500, 2, 14));
        jButton2.setOpaque(true);
        jButton2.setPreferredSize(new java.awt.Dimension(55, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(StaticData.blueBackground);

        jButton3.setBackground(StaticData.blueBackground);
        jButton3.setFont(StaticData.font13);
        jButton3.setForeground(StaticData.textWhiteColor);
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melilliselect/resources/ReloadIcon.png"))); // NOI18N
        jButton3.setText("Storia");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        jButton3.setFocusPainted(false);
        jButton3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton3.setIconTextGap(16);
        jButton3.setMargin(new java.awt.Insets(2, -500, 2, 14));
        jButton3.setOpaque(true);
        jButton3.setPreferredSize(new java.awt.Dimension(55, 25));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel7.setBackground(StaticData.blueBackground);

        jButton4.setBackground(StaticData.blueBackground);
        jButton4.setFont(StaticData.font13);
        jButton4.setForeground(StaticData.textWhiteColor);
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melilliselect/resources/SendIconSelected.png"))); // NOI18N
        jButton4.setText("Invia");
        jButton4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        jButton4.setFocusPainted(false);
        jButton4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton4.setIconTextGap(16);
        jButton4.setMargin(new java.awt.Insets(2, -500, 2, 14));
        jButton4.setOpaque(true);
        jButton4.setPreferredSize(new java.awt.Dimension(55, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBackground(StaticData.blueBackground);

        jLabel3.setBackground(StaticData.blueBackground);
        jLabel3.setFont(StaticData.font13);
        jLabel3.setForeground(StaticData.textWhiteColor);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melilliselect/resources/HeartRed.png"))); // NOI18N
        jLabel3.setText("Scelte: 4/120");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));

        jLabel4.setBackground(StaticData.blueBackground);
        jLabel4.setFont(StaticData.font13);
        jLabel4.setForeground(StaticData.textWhiteColor);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melilliselect/resources/Diamond.png"))); // NOI18N
        jLabel4.setText("Dettagli: 2");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 301, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        jPanel9.setBackground(StaticData.blueBackground);

        jButton5.setBackground(StaticData.blueBackground);
        jButton5.setFont(StaticData.font13);
        jButton5.setForeground(StaticData.textWhiteColor);
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melilliselect/resources/Settings.png"))); // NOI18N
        jButton5.setText("Impostazioni");
        jButton5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 30, 1, 1));
        jButton5.setFocusPainted(false);
        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton5.setIconTextGap(16);
        jButton5.setMargin(new java.awt.Insets(2, -500, 2, 14));
        jButton5.setOpaque(true);
        jButton5.setPreferredSize(new java.awt.Dimension(55, 25));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        updateDashboard("1", new FileExplorer());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        updateDashboard("2", new LikeFiles());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        updateDashboard("3", new LikeFiles());
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        updateDashboard("4", new Upload());
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        updateDashboard("5", new Settings());
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
