/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package melilliselect;

import java.awt.Font;
import static java.awt.Frame.MAXIMIZED_BOTH;
import static java.awt.Frame.NORMAL;

/**
 *
 * @author arsam
 */
public class TopNav extends javax.swing.JPanel {

    /**
     * Creates new form TopNav
     */
    public TopNav() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        minimizeButton = new javax.swing.JButton();
        maximizeButton = new javax.swing.JButton();
        closeButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        fileDirLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        forwardButton = new javax.swing.JButton();

        setBackground(StaticData.dashboardBackground);
        setPreferredSize(new java.awt.Dimension(100, 90));
        setLayout(new java.awt.GridLayout(0, 1));

        jPanel1.setBackground(StaticData.dashboardBackground);
        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(StaticData.dashboardBackground);
        jPanel3.setLayout(new java.awt.GridBagLayout());

        minimizeButton.setBackground(StaticData.dashboardBackground);
        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melilliselect/resources/Minimize.png"))); // NOI18N
        minimizeButton.setBorder(null);
        minimizeButton.setOpaque(true);
        minimizeButton.setPreferredSize(new java.awt.Dimension(16, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        jPanel3.add(minimizeButton, gridBagConstraints);

        maximizeButton.setBackground(StaticData.dashboardBackground);
        maximizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melilliselect/resources/Maximize.png"))); // NOI18N
        maximizeButton.setBorder(null);
        maximizeButton.setOpaque(true);
        maximizeButton.setPreferredSize(new java.awt.Dimension(13, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        jPanel3.add(maximizeButton, gridBagConstraints);

        closeButton.setBackground(StaticData.dashboardBackground);
        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melilliselect/resources/Close.png"))); // NOI18N
        closeButton.setBorder(null);
        closeButton.setOpaque(true);
        closeButton.setPreferredSize(new java.awt.Dimension(13, 20));
        closeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 20;
        jPanel3.add(closeButton, gridBagConstraints);

        jPanel1.add(jPanel3, java.awt.BorderLayout.LINE_END);

        jPanel5.setBackground(StaticData.dashboardBackground);

        fileDirLabel.setBackground(StaticData.dashboardBackground);
        fileDirLabel.setFont(new Font("Inter", Font.BOLD, 15));
        fileDirLabel.setText("USE DRIVE");
        fileDirLabel.setToolTipText("");
        jPanel5.add(fileDirLabel);

        jPanel1.add(jPanel5, java.awt.BorderLayout.CENTER);

        add(jPanel1);

        jPanel2.setBackground(StaticData.dashboardBackground);
        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 1, 1, 1));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(StaticData.dashboardBackground);
        jPanel8.setPreferredSize(new java.awt.Dimension(40, 10));
        jPanel2.add(jPanel8, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(StaticData.dashboardBackground);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setBackground(StaticData.dashboardBackground);
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melilliselect/resources/ArrowBack.png"))); // NOI18N
        backButton.setBorder(null);
        jPanel4.add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        forwardButton.setBackground(StaticData.dashboardBackground);
        forwardButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/melilliselect/resources/ArrowForward.png"))); // NOI18N
        forwardButton.setToolTipText("");
        forwardButton.setBorder(null);
        forwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forwardButtonActionPerformed(evt);
            }
        });
        jPanel4.add(forwardButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(jPanel2);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonActionPerformed

    private void forwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forwardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forwardButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel fileDirLabel;
    private javax.swing.JButton forwardButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    public static javax.swing.JButton maximizeButton;
    public static javax.swing.JButton minimizeButton;
    // End of variables declaration//GEN-END:variables
}
